### ISSUE TITLE
side menu is freezing when opening 

### ISSUE THREAD

**Issue by cgarnier** [react-native-community/react-native-side-menu#266] opened 2017-03-01 10:13 UTC
Hello,
The side menu seams to freeze when i open it.

**Comment by Kureev** [comment] 2017-07-15 20:20
Please, add some repro steps (I tried Basic example - it works for me). Closing for now as non-actionable.

**Comment by cgarnier** [comment] 2017-07-19 08:30
You can try to stress it a litle on an avd or on a android phone.

**Comment by cgarnier** [comment] 2017-07-19 10:03
https://photos.app.goo.gl/sbVyHfWxl0KA1yR43
I think it s cause by the scrollview inside the menu

**Comment by Kureev** [comment] 2017-07-19 10:03
Ok, I just tried an [example](https://github.com/react-native-community/react-native-side-menu/tree/master/examples/Basic) and it works pretty fast (even in dev mode). Please, try out an example above: if you won't encounter any issues, most likely the issue is in the codebase you're working on (maybe some complex computations during the menu opening or smth like that).

Will be closed due to additional information that will help to reproduce the issue. "Stress a little" doesn't trigger any perf issues for me.

**Comment by kingmatusevich** [comment] 2018-11-02 18:08
I have that happening, when I have a long flatlist, it gets stuttery opening for the first time, and it many cases it closes itself again.

**Comment by chakrihacker** [comment] 2020-01-28 10:19
Closing this issue, please provide steps to reproduce

**Closed by chakrihacker** 2020-01-28 10:19 UTC
Labels: needs-repro
